name: Client Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  watch:
    types: [started]
jobs:
  build-android:
    name: Build Android app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.17.5'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: build/app/outputs/apk/release/app-release.apk application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
